spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: dubbi
    password: kang8349
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: [ Google Client ID ]
            clientSecret: [ Google Client Secret ]
            scope: profile, email
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

