
server:
  port: 9001
  servlet:
    context-path : /

spring:
  profiles:
    include: jwt, oauth, ssl, datasource, imageserver #포함시킬 application files 나열

  main:
    allow-bean-definition-overriding: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB