spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database?allowPublicKeyRetrieval=true&useSSL=false
    username: DUBBI
    password: 8349
    driver-class-name: com.mysql.cj.jdbc.Driver