spring:
  security:
    form:
      login:
        enabled: false
    oauth2:
      client:
        registration:
          google:
            client-id: 1003188467403-u6fdcbb0qjbvf5m2qm70b2ie4cb6e4a2.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          kakao:
            client-id: 6f3c2e6e232367e20086f4b29ba19496
            redirect-uri: http://localhost:9001/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: none
            client-name: Kakao
            scope: profile_nickname, account_email, profile_image
          naver:
            client-id: foHeNf52g7B_54xDeUuJ
            client-secret: ddPm7SKzC4
            redirect-uri: http://localhost:9001/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: profile_image, email, name
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response