server:
  port: 9001
  servlet:
    context-path : /

spring:
  profiles:
    include: jwt,oauth, ssl, datasource-local #,datasource-local #포함시킬 application files 나열

  main:
    allow-bean-definition-overriding: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    properties:
        temp :
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true